### ISSUE TITLE
Guides: Find a proper fix for low mic volume

### ISSUE THREAD

**Issue by networkException** [t2linux/wiki#147]
As #144 removes a potential fix for low mic volume, a better way to fix this needs to be found. Just opening an issue for tracking here

**Comment by mahboobkarimian** [comment]
I created a repo times ago to increase the built-in mic volume. check it here https://github.com/mahboobkarimian/mbp-2019-Ubuntu-audio and see if it helps. Basically, it extracts the index of built-in mic index from `pacmd list-sources`.

**Comment by ckilb** [comment]
As this is open for a while and some others are also experiencing the issue, there's a no-brainer workaround which is working for me at least:
Some GUIs allow to increase the maximum volume - for KDE for example you can check "Raise maximum volume". This will also work for input devices - so you'll be able to increase the volume even more.

**Comment by networkException** [comment]
For me 150% was still pretty quiet, I since found a better workaround using pipewire and EasyEffects though. I will document that in detail and close this issue then
