### ISSUE TITLE
WiFi not working on MacBookPro15,1

### ISSUE THREAD

**Issue by Jcbjoe2021** [t2linux/wiki#155]
Been trying to get my WiFi working all day today 9-23-21

I follow https://wiki.t2linux.org/guides/wifi/ to a tee but for some reason it is not working 

I’ve even used the Mojave firmware and I get a little success I actually get a wlan0 and iwtcl can see my network. Put passcode in and I keep getting Operation Failed no errors 

When I don’t use Mojave firmware and use regular bugSur I run iwtcl and it can’t find my network. there is no wlan0 

Running journalctl -k —grep=brcmfmac shows everything is working fine with Mojave firmware 

Running same command with bigSur firmware I get error -2

is WiFi really this hard lol just wondering 

Please fix I would like to install X and use arch Linux as my main driver

**Comment by AdityaGarg8** [comment]
What’s the output of “uname -r”

**Comment by AdityaGarg8** [comment]
Also, may I know your model identifier?

**Comment by networkException** [comment]
Model identifier is in the title. Can you try using wpa_supplicant instead of iwd and modprobing brcmfmac before connecting to a network?

**Comment by Jcbjoe2021** [comment]
bash-3.2$ uname -r
19.6.0
bash-3.2$ ioreg -l | grep RequestedFiles
    | |   |       | |   "RequestedFiles" = ({"Firmware"="C-4364__s-B2/kauai.trx","TxCap"="C-4364__s-B2/kauai-X0.txcb","Regulatory"="C-4364__s-B2/kauai-X0.clmb","NVRAM"="C-4364__s-B2/P-kauai-X0_M-HRPN_V-m__m-7.7.txt"})
bash-3.2$ system_profiler SPHardwareDataType | grep "Model Identifier"
      Model Identifier: MacBookPro15,1

**Comment by AdityaGarg8** [comment]
> bash-3.2$ uname -r
> 19.6.0
> bash-3.2$ ioreg -l | grep RequestedFiles
> | | | | | "RequestedFiles" = ({"Firmware"="C-4364__s-B2/kauai.trx","TxCap"="C-4364__s-B2/kauai-X0.txcb","Regulatory"="C-4364__s-B2/kauai-X0.clmb","NVRAM"="C-4364__s-B2/P-kauai-X0_M-HRPN_V-m__m-7.7.txt"})
> bash-3.2$ system_profiler SPHardwareDataType | grep "Model Identifier"
> Model Identifier: MacBookPro15,1

uname -r had to be run on Arch

**Comment by Jcbjoe2021** [comment]
On the live iso or the installed arch I did last night?

**Comment by AdityaGarg8** [comment]
Installed Arch

**Comment by Jcbjoe2021** [comment]
The installed arch has all the modified firmware from the wiki does that matter?

**Comment by AdityaGarg8** [comment]
no

**Comment by Jcbjoe2021** [comment]
Arch install uname -r is 5.12.19-2-mbp

**Comment by Jcbjoe2021** [comment]
@networkException 

> Model identifier is in the title. Can you try using wpa_supplicant instead of iwd and modprobing brcmfmac before connecting to a network?

I will try this in the morning

**Comment by AdityaGarg8** [comment]
Get a kernel from https://github.com/jamlam/mbp-16.1-linux-wifi/releases if you want to use Big Sur firmware.

**Comment by AdityaGarg8** [comment]
Big Sur is stable afaik.

**Comment by Jcbjoe2021** [comment]
@networkException Do you want me to follow the wiki still when using wpa_supplicant just don't do systemctl restart iwd? I will google how to use wpa_supplicant

**Comment by networkException** [comment]
You follow all instructions from the wiki but use
```ini
[device]
wifi.backend=wpa_supplicant
```
in `/etc/NetworkManager/NetworkManager.conf` instead. Then run `sudo modprobe -r brcmfmac && sudo modprobe brcmfmac` and try connecting to a network

**Comment by Jcbjoe2021** [comment]
So I tried following wpa_supplicant but I errored out 

Used Mojave firmware and I got wlan0 used old ell and iwd as suggested 

I'm away from home for a few days so I had to also get wifi working on my machine. What I did is to use iwd as the guide describes but use an older version of iwd:

```bash
sudo pacman -U https://archive.archlinux.org/packages/i/ell/ell-0.39-1-x86_64.pkg.tar.zst # a required dependency for the older iwd
sudo pacman -U https://archive.archlinux.org/packages/i/iwd/iwd-1.13-1-x86_64.pkg.tar.zst
```

then ignore updates for those packages in `/etc/pacman.conf`:

```ini
IgnorePkg    = iwd ell
```

Tried that. Had to download manually on Mac to an external

Finished wiki and everything is up and running. 

When I reboot I just run systemctl restart iwd and I'm connected 

Had to download dhcpcd manually also and run it to get my ip 

Anything else you want me to try out man this completed

I would probably add a note in the wiki to try Mojave drivers on MacBookPro15,1 arch install

**Comment by Jcbjoe2021** [comment]
Update: 9-25-21

MacBookPro15,1

Used old iwd and ell

iwd-1.13-1-x86_64.pkg.tar.zst

ell-0.39-1-x86_64.pkg.tar.zst

Used Mojave firmware 

https://packages.aunali1.com/apple/wifi-fw/18G2022/C-4364__s-B2/

Used wiki for everything and everything has been working fir a straight day now 

Should I close this out? Can you guys make an excerpt on the wiki telling people if they are having issues in the MacBookPro15,1 to try what I did?

Thanks

**Comment by networkException** [comment]
Newer iwd versions causing issues is a model independent issue. The wifi guide does have a note on this but it's clearly not visible enough. I will close the issue for now

**Comment by 0xc0000007b** [comment]
Running MacBookPro15,1 here and used the [custom Archiso](https://github.com/Redecorating/archiso-mbp/releases) `r3.2898e6f` mentioned in the wiki's arch guide and had no issues connecting to wifi following the wifi guide and the steps listed to use `iwd` in the image's MOTD.
