### ISSUE TITLE
there is a way to read or even write to APFS

### ISSUE THREAD

**Issue by ildar-aim** [t2linux/wiki#171]
https://aur.archlinux.org/packages/linux-apfs-rw-dkms-git/
https://github.com/linux-apfs/linux-apfs-rw

Probably is worth to be mentioned in 
https://wiki.t2linux.org/state/#other

**Comment by AdityaGarg8** [comment]
Have you tested this on T2 Macs?

**Comment by AdityaGarg8** [comment]
The driver doesn't seem to work on my MBP 16,1

**Comment by AdityaGarg8** [comment]
No. My filevault is off.

**Comment by appleplectic** [comment]
Well, there's a way to mount ext4 partitions in MacOS - I use [fuse-ext2](https://github.com/alperakcan/fuse-ext2), and it works pretty well for Read-only support! I haven't risked writing to Linux yet...

**Comment by Redecorating** [comment]
is the stuff added in https://github.com/t2linux/wiki/commit/9296f46031fac063e7d3261d6f25f9074c390c14 enough for this?
