### ISSUE TITLE
Fedora installation guide needed?

### ISSUE THREAD

**Issue by nikodunk** [t2linux/wiki#178]
Hey there,

Thanks for the great site. I'm writing this from a fully-working (minus speakers - headphones only) t2 Macbook Air 8,2.

I followed the directions in the Ubuntu guide, but did them with the Fedora builds linked [here](https://wiki.t2linux.org/#distributions). I only had to follow the WiFi and Audio setup wikis afterwards - everything worked out of the box.

Would it be helpful if I clone the Ubuntu Installation guide, customize it to Fedora (though it literally works unchanged) and PR? Or does this increase the maintenance burden. One could also remark at the top of the Ubuntu guide that this works unchanged for Fedora too.

Thanks again!

**Comment by EmreTech** [comment]
Of course! Feel free to write a Fedora guide! (BTW, I wrote the Ubuntu guide and stole most instructions from the Manjaro instructions)

**Comment by nikodunk** [comment]
@EmreTech sweet! Thanks. 

I've written it up - can you give me branch privileges to PR?

**Comment by networkException** [comment]
There are no previleges required to open a pr, you can use a branch on a fork

**Comment by nikodunk** [comment]
Got it. Apologies. Added PR here: https://github.com/t2linux/wiki/pull/179

**Comment by Redecorating** [comment]
#179 is merged and adds a fedora guide
