### ISSUE TITLE
Wifi guide might need some improvements?

### ISSUE THREAD

**Issue by igorsantos07** [t2linux/wiki#203]
I have a Macmini8,1 and I'm dual-booting with Mint (Ubuntu-based).

While the wiki helped me with many steps on solving the wifi issues, a few things left me a bit lost / might need correction / improvements:

- it's not clear if we need to patch the current kernel to get wifi to work. There are a lot of steps involved in identifying the firmware files, but these are also a bit unclear - kernel compilation is only necessary when retrieving files from Big Sur? Is it ok to use a Mojave firmware? I'm running Monterey, got its firmware, but when loading all I had was `FW failed to load`
- then, following [this thread (and giving up and skipping to the end)](https://github.com/mikeeq/mbp-fedora-kernel/issues/3#issuecomment-924600879) I decided to download the firmware instead as suggested, and it seems to work fine...
- Except that I get stuck in a password loop (which, when googling, yields a plethora of different "solutions", no clue how to start debugging). Could this be related some missing step? I tried using iwd as suggested in the wiki (Ubuntu installs 1.5) but the iwd service can't start here. Using wpa_supplicant as backend yields the same loop (is it the default backend?)

**Comment by Redecorating** [comment]
The situation with wifi has been greatly simplified as we now have wifi firmware selection from linux working, and there is a pull request (#198) to update the wifi guide for that (not yet merged as the kernel changes for this aren't in mbp-fedora yet).

The Firmware failed to initialise is because firmware from macos versions after Mojave requires some random data as a seed (the chips don't have a hardware random number generator). The "Big Sur" kernels/patchset provides that seed to the wifi chip.

I would suggest installing this kernel, which has the automatic firmware selection, and fixes the firmware loading issue + some other bugs: https://github.com/AdityaGarg8/T2-Ubuntu-Kernel/releases/tag/v5.15.13-1 you should be able to build it yourself by cloning the repo and using `build.sh` if you don't want to use the built release there. You would also need firmware with a new naming scheme, you can use [this deb](https://cdn.discordapp.com/attachments/706581810745966653/926729551558639646/iso-firmware.deb) or get the firmware in the new format yourself by following the instructions added by #198

**Comment by igorsantos07** [comment]
Hmmm got it. I think.

Any guess which OS version are [these files (suggested on that thread)](https://packages.aunali1.com/apple/wifi-fw/18G2022/) from? These initialize fine for me; networks are listed, but connection gets stuck in a password loop.

---------

Nonetheless, I tried installing the 5.15.13 debs you liked - but I can't start from it. Will try building it tomorrow... I guess I spent too many hours on this and my body needs a bed lol
Thanks for the quick guidance!

**Comment by Redecorating** [comment]
The files hosted there are from macOS Mojave.

If you can boot back into a working kernel tomorrow, `journalctl -b -1 > last_boots_logs.txt` will save the logs from the last boot. Hopefully we can get some logs from whenever it fails to start.

@AdityaGarg8 might know a better release to use.

**Comment by AdityaGarg8** [comment]
Technically you will end up having the same files if you use build.sh so no point in building. May I know the issue you are facing with 5.15.13?

**Comment by igorsantos07** [comment]
This is a photo of [where it gets stuck](https://user-images.githubusercontent.com/532299/148351199-991b0e97-446f-42e2-b647-5196d008751b.jpg), and here is
[last_boot_logs.txt](https://github.com/t2linux/wiki/files/7820396/last_boot_logs.txt).

Do these help identifying anything? I know something on how to get around in Linux but kernels are an empty book in my mental library lol

**Comment by AdityaGarg8** [comment]
Oh, you need the `efi=noruntime` parameter @igorsantos07

**Comment by AdityaGarg8** [comment]
Or if you want, I'll make an ISO for you where wifi works out of the box?

**Comment by AdityaGarg8** [comment]
What do you think?

**Comment by igorsantos07** [comment]
I didn't spend much time installing stuff here, started by the wifi anyway, so it wouldn't hurt reinstalling the whole OS - but isn't that too much trouble for you? haha

That parameter is for.... booting? Any hint on how I should include it with rEFInd which auto-scanned my OSes? It boots fine the other kernels I tried (currently at 5.13.0-23).

**Comment by Redecorating** [comment]
That looks like a different kernel panic to the one that occurs with nvram writes, the trace has some stuff about crypto, not efi, so I don't think efi=noruntime is the issue. (also go to sleep)

I'll have a look and see if there's a module we can try blacklisting to prevent it (but go sleep first)

Tomorrow could you also check that if you boot it again, the panic (what you took a photo of) is still on the crypto stuff (it's possible that the panic could have a cause that's not specific to one piece of code)

**Comment by Redecorating** [comment]
possibly also see if a normal 5.15 kernel has the same issue (but no rush, go sleep)

**Comment by igorsantos07** [comment]
The latest kernels I can find on the Mint kernel took is 5.13, but I found some guides on how to get 5.15. Will do tomorrow. 

That pic was actually the second try - I installed, rebooted to it, it panicked, and I went back to 5.13, then tried again so I could photograph it... The first take was changing between seemingly two different panics every bunch of seconds? Will try again tomorrow _after bed_ hahaha

Thank you all! Really!

**Comment by AdityaGarg8** [comment]
Oh, sorry I didn’t see you used mint

**Comment by igorsantos07** [comment]
PS: no need for a new ISO, I guess. I recalled I had a Realtek USB wifi card, plugged it in and got a working driver from a quick googling + build.

This is really a temporary fix (so I can unplug my phone lol), but worst case scenario, it's usable in mid-term until it gets ~easier~ less painful to get the internal wifi working. So I can keep configuring the rest of my environment while I try different approaches, and finally get some work done (after 2 full days lost in this Mac war)......

**Comment by AdityaGarg8** [comment]
rEFInd probably must be showing you 2 entries. 1st is the one with the mint logo and second with the one with the Linux penguin logo. You have to use the one with the mint logo (if the linux penguin one entry is not there, needn't worry :) )
Now, boot into the kernel you are able to right now. edit `/etc/default/grub` and make sure you have
`GRUB_CMDLINE_LINUX="efi=noruntime pcie_ports=compat acpi=force intel_iommu=on iommu=pt"`

**Comment by AdityaGarg8** [comment]
after updating, run `sudo update-grub`. You may take some rest and do it later too :)

**Comment by igorsantos07** [comment]
rEFInd shows me Mint (with its multiple kernels by now) and MacOS, no extra Tux :)

Under 5.13, `/etc/default/grub` only shows this, besides the bunch of comments:

```
GRUB_DEFAULT=0
GRUB_TIMEOUT_STYLE=hidden
GRUB_TIMEOUT=0
GRUB_DISTRIBUTOR=`lsb_release -i -s 2> /dev/null || echo Debian`
GRUB_CMDLINE_LINUX_DEFAULT="quiet splash"
GRUB_CMDLINE_LINUX=""
```

Should I add all those commands? Would update-grub mess up with rEFInd somehow?

**Comment by AdityaGarg8** [comment]
A pic of refind would be helpful.

**Comment by AdityaGarg8** [comment]
which desktop environment are you using

**Comment by igorsantos07** [comment]
I customized refind's interface a bit, actually. Is there anything useful instead in /boot/efi/EFI/refind?

/boot/efi/EFI has the following folders: APPLE, BOOT, refind, tools, ubuntu.

I'm running Mint Uma, Mate edition.

I guess I should also mention my installer didn't finish 100%, since grub crashed it towards the end. Only later (by googling) I found about rEFIind, which scanned from Mac and it found Mint, surprisingly working(?) [Not sure what it's missing, if any](https://forums.linuxmint.com/viewtopic.php?f=46&t=364766), besides some dangling live stuff here and there (apt repo, installer shortcut).

**Comment by AdityaGarg8** [comment]
> I customized refind's interface a bit, actually. Is there anything useful instead in `/boot/efi/EFI/refind`? Otherwise I can get a list of anything that's bootable in my next reboot.
> 
> `/boot/efi/EFI` has the following folders, btw: `APPLE`, `BOOT`, `refind`, `tools`, `ubuntu`.
> 
> I'm running Mint Uma, Mate edition.
> 
> I guess I should also mention my installer didn't finish 100%, since grub crashed it towards the end. Only later (by googling) I found about rEFIind, which scanned from Mac and it found Mint, surprisingly working(?) [Not sure what it's missing, if any](https://forums.linuxmint.com/viewtopic.php?f=46&t=364766), besides some dangling live stuff here and there (apt repo, installer shortcut).

Installer crashed due to lack of `efi=noruntime`

You need a custom ISO

**Comment by AdityaGarg8** [comment]
I'll see if I am able to make an ISO for Mint.

**Comment by AdityaGarg8** [comment]
> I customized refind's interface a bit, actually. Is there anything useful instead in `/boot/efi/EFI/refind`? Otherwise I can get a list of anything that's bootable in my next reboot.
> 
> `/boot/efi/EFI` has the following folders, btw: `APPLE`, `BOOT`, `refind`, `tools`, `ubuntu`.
> 
> I'm running Mint Uma, Mate edition.
> 
> I guess I should also mention my installer didn't finish 100%, since grub crashed it towards the end. Only later (by googling) I found about rEFIind, which scanned from Mac and it found Mint, surprisingly working(?) [Not sure what it's missing, if any](https://forums.linuxmint.com/viewtopic.php?f=46&t=364766), besides some dangling live stuff here and there (apt repo, installer shortcut).

So it was that when the installer was trying to install, grub installation crashed, as it was trying to write the NVRAM. Then, you used rEFInd to boot Linux, cause the kernel were installed. But, refind is not at all reliable to directly boot kernels.

**Comment by AdityaGarg8** [comment]
@igorsantos07 , Try a reinstallation with https://github.com/AdityaGarg8/mbp-ubuntu/releases/tag/mint-5.15.12. The installer shouldn't probably crash now.

**Comment by AdityaGarg8** [comment]
Make sure you cleanup your old installation.

**Comment by AdityaGarg8** [comment]
Wifi should work out of the box in this.

**Comment by igorsantos07** [comment]
Now I got why you all of sudden asked my DE.
I'm really mesmerized you went all the way to create a new Mint release for me to try out. Thanks! I'm downloading it now.

In the meantime, I'm also sobbing because the MacOS decided it doesn't want to run anymore, and I don't recall making any changes to it or rEFInd that would cause Mac issues :sob: 
Any boot option like safe or single user mode cause the same dump on screen (which I'll append here as soon as I reboot with the Mint pendrive ready). The Apple Recovery option also seems to be gone from rEFInd since I upgraded to Monterey?

> Definitely regretting the day I said "ok, I'll get a Mac because I need to debug iPad issues".

**Comment by igorsantos07** [comment]
I installed Mint, but it booted to a kernel panic screen, similar to the previous ones. Tried other options inside refind, until I recalled the NVRAM issue you mentioned... Then I edited the Mint boot line to include `efi=noruntime` and.................. it's working <3

However: the Live USB was able to connect to wifi seamlessly, while in the actual install I had to re-modprobe the driver :thinking: 

Also: is there a way to make that efi boot option "permanent" in any Mint option from refind (besides permanently editing the current boot line)? I wonder if, in the future, when I upgrade to a newer kernel or something else, it will get lost again and panic.

**Comment by AdityaGarg8** [comment]
> Now I got why you all of sudden asked my DE. I'm really mesmerized you went all the way to create a new Mint release for me to try out. Thanks! I'm downloading it now.
> 
> In the meantime, I'm also sobbing because the MacOS decided it doesn't want to run anymore, and I don't recall making any changes to it or rEFInd that would cause Mac issues 😭 Any boot option like safe or single user mode cause the same dump on screen (which I'll append here as soon as I reboot with the Mint pendrive ready). The Apple Recovery option also seems to be gone from rEFInd since I upgraded to Monterey?
> 
> > Definitely regretting the day I said "ok, I'll get a Mac because I need to debug iPad issues".

To fix macOS, use the startup manager to boot it 

https://wiki.t2linux.org/guides/refind/#fixing-blank-screen-on-booting-macos-using-refind

You probably are facing this

**Comment by AdityaGarg8** [comment]
> I installed Mint, but it booted to a kernel panic screen, similar to the previous ones. Tried other options inside refind, until I recalled the NVRAM issue you mentioned... Then I edited the Mint boot line to include `efi=noruntime` and.................. it's working <3 I had to re-modprobe at the first login, but only then.
> 
> It's even showing the fan sensor, which wasn't present before (actually, together with other 31 temperature(?) sensors, from TA0V to TW2P and TaRC)
> 
> Also: is there a way to make that efi boot option "permanent" in any Mint option from refind (besides permanently editing the current boot line)? I wonder if, in the future, when I upgrade to a newer kernel or something else, it will get lost again and panic.
> 
> And no progress with the Mac panic yet (didn't google much yet, though): ![image](https://user-images.githubusercontent.com/532299/148433731-ab0aa2ed-3877-447a-bf9e-219c519b238d.png)

Firstly, did the installation crash this time?

If no, is refind showing an entry to boot grub? It probably should be the one with the linux mint logo instead of the linux penguin one.

**Comment by igorsantos07** [comment]
Nope, no crash! Installation was successful!
It's missing the sound support, though. I've tried adding the PulseAudio files, but no success yet... Gonna reboot soon to check if it works.

The Mint entry in refind points to `/boot/vmlinuz-5.15.12-t2`. Here are the possibly relevant entries (moved the correct Mint entry, the selected one, to the hidden tags so I could list them all together):
![image](https://user-images.githubusercontent.com/532299/148492964-9bbd7ea2-c972-4abd-9c74-dcc48fda23c3.png)

I'm not sure what's that `ubuntu/grubx64.efi` entry. Maybe a leftover from the initial failed install?

**Comment by AdityaGarg8** [comment]
@igorsantos07 , probably, the Ubuntu one entry shall be the one which shall boot grub for mint. Could you try that?

**Comment by igorsantos07** [comment]
Just tested - that Ubuntu entry (which appropriately gets an Ubuntu logo) seems to just go into a Linux Mint logo that gets stuck? Let me check if it also needs `efi=noruntime`...

The one that I've been using so far to boot - and that I need to edit every time - is the vmlinuz one.

----

The force-to-boot-MacOS trick seems to have worked :) I've submitted a tiny PR since I needed trial-and-error to "find" the Option key lol

**Comment by AdityaGarg8** [comment]
@igorsantos07 , edit `/etc/default/grub` and make sure `GRUB_CMDLINE_LINUX="efi=noruntime pcie_ports=compat acpi=force intel_iommu=on iommu=pt"` is there instead of `GRUB_CMDLINE_LINUX=" "`. Do the editing and run `sudo update-grub`. Then the Ubuntu option in refind should be fixed.

**Comment by igorsantos07** [comment]
Nice! That worked too - I'll swap it with the previous Mint option.

Lastly, any idea on how to get the sound jack to work? It's playing great on the Mac OS, but inside Mint all I see is the HDMI output (which I can't test since my screen has no sound anyway). I just created the files from [the first link](https://gist.github.com/MCMrARM/c357291e4e5c18894bea10665dcebffb) on [the guide](https://wiki.t2linux.org/guides/audio-config/#audio-configuration-files) (even made the copy mentioned later in the comments), but no dice. I even restarted to see if PulseAudio would catch the correct stuff (otherwise, would `pulseaudio -k` do the trick after a few seconds for it to auto-restart, I guess?).

I also find nothing recent about pulseaudio or alsa in `syslog`. Any idea where to start debugging this?
I tried `pulseaudio -k; pulseaudio -v --start --log-target=newfile:/tmp/pulse.log --daemonize=no`, but it doesn't seem to output anything (and I know it's reloading because my webcam, which has a built-in mic, blinks).

**Comment by AdityaGarg8** [comment]
@igorsantos07 , in settings>sounds, is there something like codec-output. If yes, change to that.

**Comment by igorsantos07** [comment]
Nope, it just shows the HDMI option - which doesn't seem to behave either, since I found a volume control on my display's internal menu.
![image](https://user-images.githubusercontent.com/532299/148506956-b308ac41-0e0a-4453-832a-b0a5b76d7a6f.png)


If I permanently kill pulseaudio, that screen shows `HDA Intel PCH` as an output option, but without being able to configure volumes and such. It also lists my webcam as output, which is wrong since it has a mic, but not a speaker.
![image](https://user-images.githubusercontent.com/532299/148506868-9fc9c46a-babe-4a6e-939b-9d6086755c06.png)

**Comment by AdityaGarg8** [comment]
@Redecorating , please help

**Comment by Redecorating** [comment]
Have you followed https://t2linux.org/guides/audio-config/ ? Does ‘lsmod | grep apple_bce‘ show apple_bce?

The files in the audio guide might need changing as the speaker layout on mac mini would be different (does it even have a speaker, or is it just the 3.5mm audio jack)

**Comment by AdityaGarg8** [comment]
Mac mini doesn't have a speaker afaik.

**Comment by AdityaGarg8** [comment]
Oh it has!!

**Comment by AdityaGarg8** [comment]
https://www.apple.com/in/mac-mini/specs/

**Comment by igorsantos07** [comment]
Yep, it has an internal speaker - terrible, but does hahaha
There's also a combo(?) jack - although I'm mostly interested in the speaker part of it.

I've followed the guide, yes, and even created the copy for the other alsa file as described in comments.

And no `apple_bce` shown by lsmod :thinking: 

Gonna add other possibly useful debug information that I saw around forums...

**Comment by AdityaGarg8** [comment]
Should be `lsmod | grep apple-bce` Not apple_bce

**Comment by AdityaGarg8** [comment]
Please try again

**Comment by igorsantos07** [comment]
Still nothing :cry: 
![image](https://user-images.githubusercontent.com/532299/148590814-ddd411a3-7636-4d1f-8508-07e8121387a9.png)

**Comment by Redecorating** [comment]
try `sudo modprobe apple_bce`, if it says that that module doesn't exist, follow https://wiki.t2linux.org/guides/dkms/#installing-modules to get apple-bce, which handles internal audio, and shows some system usb devices

**Comment by igorsantos07** [comment]
Non-existent module, indeed.

However... files were already present, including `dkms.conf`. I guess these came with the ISO @AdityaGarg8 gave me?
These were the missing steps, indeed :) I'll add these clarifications to the guide.
Uh... Any chance these sound settings could affect microphone quality on an USB webcam? I didn't think about testing it before, but it's sounding horrible and I'm not sure if it's because it's plugged in a hub haha

Anyhow... I guess I'm done here! Everything seems to be working <3
I'm just not sure how to improve the guides in relation to the issues I had in the beginning, such as the wifi and the need of `efi=noruntime`. Leave the issue open if you're going to figure out improvements later... Otherwise, it can be closed :)

Thank you all so much for the guidance and work!

**Comment by AdityaGarg8** [comment]
You may close it cause the `efi=noruntine` issue is known already and has been included in our T2 specific ISOs. Cause you wanted mint, it got a bit complicated cause we don't have an ISO for mint yet.
