### ISSUE TITLE
Slow Wifi on Kubuntu and  a workaround for it 

### ISSUE THREAD

**Issue by ckilb** [t2linux/wiki#273]
First I have to say thanks for the t2linux wiki. Great job! I didn't expect to have Linux properly running on my machine until I followed the steps of the Wiki and nearly everything was instantly working. This is awesome.

I installed Ubuntu with Gnome first and had - of course - no Wifi at all initially, but following your guide I was able to get a connection. It was fast and the ping was low. Later on I decided to switch to Kubuntu and did a fresh install of that. Again I followed your guide, again I had some connection but now it was quite bad:

Ubuntu Wifi performance: ~ 260 MBit/s, Ping ~7ms 
Kubuntu Wifi performance: ~ 40-50 MBit/s, Ping 12 - 15ms

Both measured via fast.com

I have no idea why different user interfaces (Gnome vs KDE) have different Wifi performances, maybe that's not the case and there's another reason for that.

But: I could fix it by **disabling ipv6**.

1. Check if ipv6 is actually enabled by typing **ip a** in terminal and cneck if there's an entry **inet6** for **wlan0** - if not, ipv6 is not active
2. Add some script and save it to for instance ~/startup/disable-ipv6.sh with following content:

> #!/bin/bash

> sysctl -w net.ipv6.conf.all.disable_ipv6=1
> sysctl -w net.ipv6.conf.default.disable_ipv6=1
> sysctl -w net.ipv6.conf.lo.disable_ipv6=1
> 
> echo 1 > /proc/sys/net/ipv6/conf/default/disable_ipv6
> echo 1 > /proc/sys/net/ipv6/conf/all/disable_ipv6
> 
> exit 0

3. Add a cronjob to execute that script every minute:

Type **sudo crontab -e** in terminal - then add new line:
`* * * * * /home/username/startup/disable-ipv6.sh`

4. Wait a minute, type **ip a** again and check if inet6 entries disappeared

That's all.

For sure there's a smarter way to execute that script than a cronjob running every minute. But this was the only thing that worked for me. I also tried with @reboot inside crontab, I tried adding it to /etc/rc.local and some more things. Nothing worked.

Maybe it's worth adding that into the Wiki.

My machine:
Macbook Pro 2018 15" with i7
A1990
BCM4364 802.11ac Wireless Network Adapter

**Comment by AdityaGarg8** [comment]
Sorry for the late reply.

I'd like to know which ISO did you use for Kubuntu?

**Comment by AdityaGarg8** [comment]
Again, no reply yet so closing this.
