### ISSUE TITLE
Backlight config suggestion

### ISSUE THREAD

**Issue by willjp** [t2linux/wiki#275]
Hey friends! I have a suggestion for the docs.

If you're using a hybrid graphics setup, you can configure `Xorg` to use a specific `/sys/class/backlight/` directory to manage brightness. This makes tools like `xorg-xbacklight` work.

```conf
# /etc/X11/xorg.conf.d/10-backlight.conf

Section "Device"
        Identifier "Card0"
        Driver "intel"
        BusID "PCI:0:2:0"
        Option "Backlight" "acpi_video0"  # <-- /sys/class/backlight/${DIRNAME}
EndSection
```

**Comment by AdityaGarg8** [comment]
You probably can open a PR if you want to get it added to the wiki.

**Comment by AdityaGarg8** [comment]
There have been changes to backlight configurations in recent kernels. Do you still think its relevant? Also, we ultimately shall be using gmux-backlight for hybrid graphics.

**Comment by Redecorating** [comment]
For kernel versions 6.1.12-2 and above, we will always only have one backlight class device, so we won't need to specify which to use, as the only present one will be the right one.

If it's still not working by default on t2 kernels with versions higher or equal to 6.1.12-2, please reopen this so we can figure it out.
