### ISSUE TITLE
Please help me with this signature error...

### ISSUE THREAD

**Issue by Ahmed97i** [t2linux/wiki#281]
![image](https://user-images.githubusercontent.com/71390035/165419577-8d6759e1-6122-45fb-b05d-c22b8a2e1b2f.jpeg)

**Comment by AdityaGarg8** [comment]
Cc @Redecorating @NoaHimesaka1873

**Comment by NoaHimesaka1873** [comment]
@AdityaGarg8 He emailed me so I sent him a reply with an instruction.

**Comment by AdityaGarg8** [comment]
Then I'll close this.
