### ISSUE TITLE
Stuck on kernel 5.10.47. Trying to find patches for 5.15.0-41

### ISSUE THREAD

**Issue by fetushito** [t2linux/wiki#301]
After successfully patching the 5.10.47 kernel (https://github.com/t2linux/wiki/issues/67) I need some help finding the right patches for later kernel versions, 5.15.0-41 to be specific.

Any guidance you can provide is much appreciated.

**Comment by fetushito** [comment]
I don´t want to be stuck in an old kernel version, as there could be security implications if I'm not wrong.

**Comment by fetushito** [comment]
Thank you @AdityaGarg8 - would be nice if you can make a new repo for the 5.15 patches. Or even better, if you could teach me how to do it so I can do it on my own going forward.

**Comment by AdityaGarg8** [comment]
I actually maintain a repo of patches for the latest mainline in https://github.com/AdityaGarg8/linux-t2-patches.

For 5.15, I checkout the an old commit hash + some other changes which the script to compile the kernel does for me.

In short, I'll run the scoto compile the kernel and get the patches from there.

**Comment by fetushito** [comment]
@AdityaGarg8 - Please don´t forget about this one :pray:

**Comment by AdityaGarg8** [comment]
Sorry, I forgot about this. I'll get it done today.

**Comment by AdityaGarg8** [comment]
The 5.15 branch should be good :- https://github.com/AdityaGarg8/linux-t2-patches/tree/5.15

If anything breaks after upgrading to 5.15, you may mention it here, cause your kernel is too old and there could have been changes made in the drivers by us.

**Comment by AdityaGarg8** [comment]
@fetushito , if your issue is resolved, shall I close it?
