### ISSUE TITLE
Experience concerning rEFInd blank screen

### ISSUE THREAD

**Issue by Akronae** [t2linux/wiki#309]
In the [rEFInd documentation](https://wiki.t2linux.org/guides/refind/#fixing-blank-screen-on-booting-macos-using-refind), an issue about rEFInd being stuck on a white screen is discussed.
It happened to me, and would not work back even after a proper successful boot.
What worked for me with was to surprisingly theme my rEFInd ([using the Minimal Theme](https://github.com/evanpurkhiser/rEFInd-minimal)) and I was able to properly navigate the menu to boot into Ubuntu.

I thought it might help people in the same situation if it appeared on the doc, though it's just my use case and might be unreliable.

**Comment by AdityaGarg8** [comment]
Haven’t seen this issue with any other user yet, seems to be unreliable.
