### ISSUE TITLE
I've added a guide for Tails (i.e. Debian proper) - want to link it as a distro in the t2linux wiki?

### ISSUE THREAD

**Issue by T2minator** [t2linux/wiki#31]
I just created this: https://github.com/T2minator/mbp-tails

Thank you for all the work you and everyone have done so far! It helped me a lot.

Why my Tails guide may be useful to list under 'distributions' at https://wiki.t2linux.org/ (alongside mbp-ubuntu, mbp-fedora, linux-mbp-arch, mbp-majnaro):

- Tails is a well-known and respected distro in its own right.

- My steps are a good reference for patching a live Debian disk to work with T2 machines (Tails = Debian Live). There was no guide on the Internet for doing it start to finish, I had to make mine. It fills a gap

- My instructions are another alternative to https://wiki.t2linux.org/distributions/ubuntu/building/ - may help Debian-based or Debian-like users looking for more than one way to compile the kernel, since it's so new for them and there's a lot to learn, try, and troubleshoot.

- Ubuntu really is quite different to Debian proper when you get into the details. And although there's a ton of Tails anonymity safety tips as appropriate for that distribution, my steps = 'Debian'.

- Since Tails keeps its kernel quite recent, I'll help document how aunali1's continual patches work, for Debian-based systems. If anything goes south, I'll be the first to let everyone know. I will be a daily T2Tails user.

- I have unique insights to offer: aligned with my particular use case (of paranoid privacy and anonymity), I will be disconnecting most of the T2-connected internal hardware in my 2019 MBP. As a side benefit, this may have an effect to reduce or even eliminate the dreaded kernel panics altogether - I'll find out. Has anyone tried that with T2 hardware yet? Maybe I'll be the first.

- I might also evolve to modifying an existing ISO (or making one) with helpful steps (not just a monolithic script), which is yet another gap not filled yet (in the t2linux wiki). It may however be a little too specific to the Tails process of making an ISO.

- I'm open to making my instructions or eventual 'T2Tails' ISO feature to be complete for all aspects of T2 hardware (including Wifi), if others test it at least.

I am still early on in daily Linux T2 / kernel crash life, but expect to find out and will document tips in my README.

Cheers!

**Comment by networkException** [comment]
First of all its always great to see people working on better support for t2 machines of course, so thank you for looking into it!

I read through your guide (at least until the first acknowledgements, I'm unsure why instructions are duplicated in the readme) and I'm happy to add it to the list of distributions as you wished.

Two few things I thought about while reading the guide and your issue:

- Regarding the alternative for distributions/ubuntu/building I'm a bit confused. Do you want to also provide a guide in lets say distributions/tails/building or similar? If not (which is fine of course) viewing your patching and compiling instructions as an alternative is a little weird, I imagine people will usually not look at each "mbp-" repo on the index page for compile instructions. Also described in #26, we are planning to write a general purpose guide anyways.
- There is a bit of duplication with your guide and our guides (especially regarding kernel modules). The idea of this wiki in general was to have one single place for documentation all around linux on t2 machines and being able to update this documentation as changes need to be made. Sadly many of the "mbp-distroname" repositories have a problem with outdated and incomplete information, so I would in your case also encourage to just link the guides as well as contribute to our guides if intructions need to be different / are outdated.

**Comment by T2minator** [comment]
Hi again,

> I'm unsure why instructions are duplicated in the readme

Not sure what you're referring to? Next time I revise it during the next Tails version (4.19), I'll probably pick it up myself if it's actual instructions duplicated.

> I'm a bit confused. Do you want to also provide a guide in lets say distributions/tails/building or similar? If not (which is fine of course) viewing your patching and compiling instructions as an alternative is a little weird

> There is a bit of duplication with your guide and our guides (especially regarding kernel modules). The idea of this wiki in general was to have one single place for documentation all around linux on t2 machines and being able to update this documentation as changes need to be made

Right. 

The problem is that the exact patching or building instructions really are different for different distros (to get it all working from start to finish).

For Tails users there's safety reasons why one can't just use existing Ubuntu instructions if one wants to patch Tails and be close to its default safety.

I'd say the logical thing is if a distro is added at https://wiki.t2linux.org/#distributions, it should be a link to a reliable, relatively easy way to either build and/or download a ready-made image for that named distro - to do what it says on the tin, and be up-to-date (current). My README does that for Tails. Want to add `Tails`? Mine is that guide.

In fact to keep up with Tails (and be safe by not using an older / non-security-patched kernel), I'll have to be on my feet, updating it eacg month (Tails generally releases monthly). I use Tails as my daily driver, so unless I stop using a T2 machine, I see no reason why I'll fail to keep `mbp-tails` current and optimised. I'd let you know if I stopped maintaining it.

For your consideration...

**Comment by networkException** [comment]
Ok I think I understand better now, I see why its required for a distribution like Tails to provide different instructions for security reasons. Still I'd encourage you to also help improve our documentation in case some information is applicable in general.

> Not sure what you're referring to? Next time I revise it during the next Tails version (4.19), I'll probably pick it up myself if it's actual instructions duplicated.

There seems to be a copy of all instructions in the readme, the starts [here](https://github.com/T2minator/mbp-tails#t2tails) and the second [here](https://github.com/T2minator/mbp-tails#t2tails-1). The duplication is also quite apparent when looking at the readme structure (the botton on the top left)
![image](https://user-images.githubusercontent.com/42888162/119259374-52b23580-bbce-11eb-9a2c-e4beae311d44.png)

**Comment by networkException** [comment]
Closing this as Tails has been added to the index file
