### ISSUE TITLE
modprobe: FATAL: Module hci_bcm4377 not found.

### ISSUE THREAD

**Issue by lukehayes** [t2linux/wiki#358]
I'm trying to get the WiFi working on  my installation of Ubuntu(I'm using the T2 version) and I am following the guide from [theWiFi guide on the t2linux website](https://wiki.t2linux.org/guides/wifi-bluetooth/).

I have have successfully ran the firmware.sh script on MacOS but when I run it on Linux I get this error:
```
Detected Linux
Re-mounting the EFI partition
Getting Wi-Fi and Bluetooth firmware
Setting up Wi-Fi and Bluetooth
modprobe: FATAL: Module hci_bcm4377 not found.
```
I am using a 2019 iMac, 19,1 model with Monterey freshly installed.

Is there anything I can do to fix this?

**Comment by AdityaGarg8** [comment]
Whats `uname -r`

**Comment by lukehayes** [comment]
@AdityaGarg8 

I have just switched from the Ubuntu-t2 ISO to the EndevourOS-t2 ISO and I am getting a completely different error. I will close this and open a new issue relating to that one.
