### ISSUE TITLE
Loss of keyboard and mouse

### ISSUE THREAD

**Issue by Stormaggedd0n** [t2linux/wiki#373]
*computer(2019 MBP) accepts t2 iso
*keyboard and trackpad also work
*try to run management software required by my work
*after running management script, Wi-Fi, keyboard and trackpad now not functional.
 
 is there a script to call them manually?

I have had to re-install a couple of times because random stuff will turn off keyboard and trackpad and I can’t get them back

**Comment by Redecorating** [comment]
Does wifi keyboard and trackpad stop working immediately after the script runs, or do you need to reboot before it stops working? What linux distro are you using? And are you able to send a kernel log (`journalctl -k > logs.txt`)?

> is there a script to call them manually?

there isn't really a script, but the kernel modules needed are: `brcmfmac` for wifi, `apple-bce`, `hid-apple` and `bcm5974` for keyboard and trackpad, so maybe some of those need loading (`sudo modprobe <module_name>`), had errors (which could be in that log), or were modified by the script (maybe it changes your kernel to one provided by your work? check if `uname -r` has "t2" in it.)

**Comment by AdityaGarg8** [comment]
Closing it as since there is no response yet.
