### ISSUE TITLE
Balena Etcher Privacy Concerns

### ISSUE THREAD

**Issue by vi-improved** [t2linux/wiki#375]
I noticed that the Pre-Install guide on the wiki recommends Balena Etcher as a GUI program to flash bootable USB drives. I understand that Etcher is a user-friendly program, however I don't think it should be recommended due to their rocky privacy track record. https://github.com/balena-io/etcher/issues/2057 shows that Etcher sends requests on startup unprompted (at least without an explicit opt-out). This is questionably in violation of the GDPR. The ArchWiki puts Etcher under "Inadvisable methods" on [this page](https://wiki.archlinux.org/title/USB_flash_installation_medium#Inadvisable_methods) because of analytics and first-party advertising. As an alternative, [USBImager](https://gitlab.com/bztsrc/usbimager/) would probably be good.

**Comment by AdityaGarg8** [comment]
Looking at the issues, it seems to be overhyped as a spyware even though it just uses trackers.

But is only Etcher having trackers? I don't think so. You browse the internet everyday and various websites use trackers imo. People who are too privacy concerned use blockers in form of private DNS or VPNs.

So I don't think we should remove Balena Etcher from the wiki, although you can simple add USBImager in the list of suggested options, provided you have tested that. And we also have dd, the one with no chances of trackers.

I'd still cc @Redecorating and @networkException for their views.

**Comment by networkException** [comment]
I think we should at least have a more privacy friendly option that doesn't require a full blown webbrowser underneath but I'm generally not against also listing Etcher

**Comment by Redecorating** [comment]
USBImager does look quite good, so I'd like to see that added. I do notice that [Ubuntu recommends Etcher still](https://ubuntu.com/tutorials/install-ubuntu-desktop#3-create-a-bootable-usb-stick) in their install instructions, so I don't really want to remove what one of our main distros recommends to their users. Having both and a note about privacy concerns and download size probably would be good?

**Comment by AdityaGarg8** [comment]
Open a PR if you want to get this fixed @vi-improved
