### ISSUE TITLE
Touchbar not working

### ISSUE THREAD

**Issue by Injng** [t2linux/wiki#377]
Hello,

I recently installed EndeavourOS (offline install) on my 2018 MBP (15 inch) by following the directions on the wiki; however, after installation, the touchbar does not work (i.e. it seems to be completely turned off/black screen). What is also of note is that the bar did momentarily turn on the first time I booted into linux, but turned off and has stayed off (no matter how many reboots) ever since.

Therefore, I followed the [instructions](https://wiki.t2linux.org/guides/postinstall/) for configuring after install. I am using `systemd-boot`, so I appended `intel_iommu=on iommu=pt pcie_ports=compat` to the options line (config file in `/efi/loader/entries`). I ran `echo apple-bce | sudo tee /etc/modules-load.d/t2.conf`, then restarted and ran the script for setting up the touch bar as indicated in the wiki.

However, upon running `sudo touchbar`, it gives the following error:

```
bash: line 1: /sys/class/input/*/device/fnmode: No such file or directory
```

and the touchbar is still off.

I did realize that the driver `apple_ib_tb` was missing, so I installed them following the directions here: https://github.com/t2linux/apple-ib-drv

However, it does not seem to work.

Any help would be greatly appreciated!

**Comment by AdityaGarg8** [comment]
We do not use apple-ib-tb now so please remove that first.

After removing that, share `lsusb`

**Comment by Injng** [comment]
Here it is:
```
Bus 007 Device 004: ID 05ac:027c Apple, Inc. Apple Internal Keyboard / Trackpad
Bus 007 Device 003: ID 05ac:8103 Apple, Inc. Headset
Bus 007 Device 002: ID 05ac:8262 Apple, Inc. Ambient Light Sensor
Bus 007 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 002 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 006 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 005 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 004 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 003 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
```

**Comment by AdityaGarg8** [comment]
Looks like Linux isn't recognising your touchbar at all. Can you try booting into the macOS Recovery and then back to Linux.

**Comment by Injng** [comment]
Thanks so much for the help! It worked after I booted into macOS Recovery and then Linux.

**Comment by Injng** [comment]
Thanks so much for the help! It worked after I booted into macOS Recovery and then Linux.
