### ISSUE TITLE
Touchbar stop working after lid closed

### ISSUE THREAD

**Issue by Tyflomate** [t2linux/wiki#388]
Hello ! 

First of all thank you for this amazing repo which saved my life to setup ubuntu on my mac, but I still have a problem with the touchbar. When I boot it works well but as soon as I close the lid, it locks and shut down the touch bar and does not work anymore. I need to reboot to make it work again. It also might be good to mention that after I close the lid and I open again, the login screen takes some time to appear. My guess is that it tries to launch the touchbar but is unable to do so. 
This issue does not seem to happen when I lock with win+l. I'm on a Macbookpro16,1 with ubuntu 22.04.

Thanks for your help !

**Comment by AdityaGarg8** [comment]
Also, `journalctl -k --grep=touchbar`

**Comment by Tyflomate** [comment]
Here you go:

```
➜  ~ uname -r
6.1.8-t2-jammy
➜  ~ journalctl -k --grep=touchbar
févr. 01 12:54:06 tyflomate-MacBookPro kernel: apple-touchbar 0003:05AC:8302.0007: input: USB HID v1.01 Keyboard [Apple Inc. Touch Bar Display] on usb-bce-vhci-6/input0
févr. 01 12:54:06 tyflomate-MacBookPro kernel: apple-touchbar 0003:05AC:8102.0008: : USB HID v1.01 Device [Apple Inc. Touch Bar Backlight] on usb-bce-vhci-7/input0
févr. 01 12:55:14 tyflomate-MacBookPro kernel: apple-touchbar 0003:05AC:8302.0007: tb: Failed to set touch bar display to 4 (-113)
févr. 01 12:55:14 tyflomate-MacBookPro kernel: apple-touchbar 0003:05AC:8302.0007: tb: Touchbar suspended.
févr. 01 15:03:40 tyflomate-MacBookPro kernel: apple-touchbar 0003:05AC:8302.0007: tb: Touchbar suspended.
févr. 01 15:03:40 tyflomate-MacBookPro kernel: apple-touchbar 0003:05AC:8302.0007: tb: Failed to set touch bar display to 4 (-108)
févr. 01 15:03:40 tyflomate-MacBookPro kernel: apple-touchbar 0003:05AC:8302.0007: tb: Touchbar suspended.
févr. 02 12:01:19 tyflomate-MacBookPro kernel: apple-touchbar 0003:05AC:8302.0007: tb: Touchbar suspended.
févr. 02 12:01:19 tyflomate-MacBookPro kernel: apple-touchbar 0003:05AC:8302.0007: tb: Touchbar suspended.
```
> And, does pressing fn key when it works, changing the touchbar modes?
Weirdly it does on login screen but not after login ... But I might have messed up something because it used to work

Tanks for your help !

**Comment by AdityaGarg8** [comment]
> Weirdly it does work on login screen but not after login ... But I might have messed up something because it used to work

Looks like touchbar is not initialising properly.

First of all, [update your kernel](https://github.com/t2linux/T2-Ubuntu-Kernel/#using-the-kernel-upgrade-script). After you run that kernel update script, boot into the macOS recovery. When it boots into the recovery, simply restart into Linux.

After that, check whether pressing fn is changing touchbar modes or not after login. When you belive that the touchbar modes are now changing properly, then try suspending, and share your results.

Send `journalctl -k --grep=touchbar` after resuming from suspend again.

**Comment by Tyflomate** [comment]
I updated without problems the kernel and rebooted in recovery then ubuntu, but the fn key still does not switch mode. I did a `sudo touchbar` with mode 1 and reboot but still does not change modes. But the touchbar now seems to work after suspend ! 
```
➜  ~ uname -r
6.1.9-t2-jammy
➜  ~ journalctl -k --grep=touchbar
févr. 02 14:44:21 tyflomate-MacBookPro kernel: apple-touchbar 0003:05AC:8302.0007: input: USB HID v1.01 Keyboard [Apple Inc. Touch Bar Display] on usb-bce-vhci-6/input0
févr. 02 14:44:21 tyflomate-MacBookPro kernel: apple-touchbar 0003:05AC:8102.0008: : USB HID v1.01 Device [Apple Inc. Touch Bar Backlight] on usb-bce-vhci-7/input0
févr. 02 14:45:32 tyflomate-MacBookPro kernel: apple-touchbar 0003:05AC:8302.0007: tb: T2 Mac detected. Touchbar suspend to be handled by Apple BCE.
févr. 02 14:45:32 tyflomate-MacBookPro kernel: apple-touchbar 0003:05AC:8302.0007: tb: T2 Mac detected. Touchbar suspend to be handled by Apple BCE.
```
Yet the login screen still takes a long time to show, I don't know if it's related

**Comment by AdityaGarg8** [comment]
By any chance, are you using an external mouse/keyboard as well?

**Comment by AdityaGarg8** [comment]
And can you share the contents of all the .conf files in `/etc/modules-load.`

**Comment by Tyflomate** [comment]
> By any chance, are you using an external mouse/keyboard as well?

Not currently but I can

> And can you share the contents of all the .conf files in /etc/modules-load.d

```
➜  ~ ls /etc/modules-load.d                
cups-filters.conf  modules.conf
➜  ~ cat /etc/modules-load.d/cups-filters.conf 
# Parallel printer driver modules loading for cups
# LOAD_LP_MODULE was 'yes' in /etc/default/cups
lp
ppdev
parport_pc
➜  ~ cat /etc/modules-load.d/modules.conf 
# /etc/modules: kernel modules to load at boot time.
#
# This file contains the names of kernel modules that should be loaded
# at boot time, one per line. Lines beginning with "#" are ignored.
```

**Comment by AdityaGarg8** [comment]
Try this

```
echo "blacklist apple-touchbar" | sudo tee /etc/modprobe.d/apple-tb.conf
```

This will blacklist the touchbar driver.

After that, shut down and power on the Mac. Boot into Linux. The touchbar should not light up. If it is, then reboot into macOS recovery and back to Linux. If it still is lighting up, then tell me. If it doesn't light up on boot, then login and run `sudo modprobe apple-touchbar`. The touchbar should light up after running this. Then tell me whether pressing fn changes touchbar modes or not.

**Comment by AdityaGarg8** [comment]
Btw is your macOS up to date?

And share `cat /proc/cmdline` as well

**Comment by Tyflomate** [comment]
Unfortunately fn still doesn't want to change touchbar status :/ My macOS is up to date and here is my output of cmdline:
```
➜  ~ cat /proc/cmdline
BOOT_IMAGE=/boot/vmlinuz-6.1.9-t2-jammy root=UUID=3f9efa86-1b8c-41e1-a6d0-bca150b3c7ef ro quiet splash vt.handoff=7
```
Thanks for your reactivity, really appreciate it :ok_hand:

**Comment by AdityaGarg8** [comment]
When you did the tests I said, was the touchbar blank in the next boot. If it was, did it atleast light up upon running `modprobe apple-touchbar`

**Comment by AdityaGarg8** [comment]
> ```
> ➜  ~ cat /proc/cmdline
> BOOT_IMAGE=/boot/vmlinuz-6.1.9-t2-jammy root=UUID=3f9efa86-1b8c-41e1-a6d0-bca150b3c7ef ro quiet splash vt.handoff=7
> ```

Looks like you used an official ISO to install Ubuntu instead of the T2 ISO. Could you add the `intel_iommu=on iommu=pt` to your command line by editing `/etc/default/grub` followed by running `sudo update-grub`

**Comment by AdityaGarg8** [comment]
After that try the macOS recovery thing again

**Comment by Tyflomate** [comment]
> When you did the tests I said, was the touchbar blank in the next boot. If it was, did it atleast light up upon running modprobe apple-touchbar

It did light up after `modprobe` but no change with fn key

> Looks like you used an official ISO to install Ubuntu instead of the T2 ISO.

Yes indeed, I wasn't aware of this T2 thing before installing ubuntu :/ 
I did update  `/etc/default/grub` and here is the result:
```
➜  ~ sudo gedit /etc/default/grub
[sudo] Mot de passe de tyflomate : 

** (gedit:16964): WARNING **: 12:01:25.152: Set document metadata failed: La définition de l’attribut metadata::gedit-spell-language n’est pas prise en charge

** (gedit:16964): WARNING **: 12:01:25.152: Set document metadata failed: La définition de l’attribut metadata::gedit-encoding n’est pas prise en charge

** (gedit:16964): WARNING **: 12:01:28.574: Set document metadata failed: La définition de l’attribut metadata::gedit-position n’est pas prise en charge
➜  ~ sudo update-grub
Sourcing file `/etc/default/grub'
Sourcing file `/etc/default/grub.d/init-select.cfg'
Generating grub configuration file ...
Found linux image: /boot/vmlinuz-6.1.9-t2-jammy
Found initrd image: /boot/initrd.img-6.1.9-t2-jammy
Found linux image: /boot/vmlinuz-6.1.8-t2-jammy
Found initrd image: /boot/initrd.img-6.1.8-t2-jammy
Found linux image: /boot/vmlinuz-5.15.0-58-generic
Found initrd image: /boot/initrd.img-5.15.0-58-generic
The ZFS modules are not loaded.
Try running '/sbin/modprobe zfs' as root to load them.
Some pools couldn't be imported and will be ignored:
The ZFS modules are not loaded.
Try running '/sbin/modprobe zfs' as root to load them.
The ZFS modules are not loaded.
Try running '/sbin/modprobe zfs' as root to load them.
The ZFS modules are not loaded.
Try running '/sbin/modprobe zfs' as root to load them.
Memtest86+ needs a 16-bit boot, that is not available on EFI, exiting
Warning: os-prober will not be executed to detect other bootable partitions.
Systems on them will not be added to the GRUB boot configuration.
Check GRUB_DISABLE_OS_PROBER documentation entry.
done
➜  ~ cat /proc/cmdline
BOOT_IMAGE=/boot/vmlinuz-6.1.9-t2-jammy root=UUID=3f9efa86-1b8c-41e1-a6d0-bca150b3c7ef ro quiet splash vt.handoff=7
➜  ~ cat /etc/default/grub
# If you change this file, run 'update-grub' afterwards to update
# /boot/grub/grub.cfg.
# For full documentation of the options in this file, see:
#   info -f grub -n 'Simple configuration'

GRUB_DEFAULT=0
GRUB_TIMEOUT_STYLE=hidden
GRUB_TIMEOUT=0
GRUB_DISTRIBUTOR=`lsb_release -i -s 2> /dev/null || echo Debian`
GRUB_CMDLINE_LINUX_DEFAULT="quiet splash"
GRUB_CMDLINE_LINUX=""

# Uncomment to enable BadRAM filtering, modify to suit your needs
# This works with Linux (no patch required) and with any kernel that obtains
# the memory map information from GRUB (GNU Mach, kernel of FreeBSD ...)
#GRUB_BADRAM="0x01234567,0xfefefefe,0x89abcdef,0xefefefef"

# Uncomment to disable graphical terminal (grub-pc only)
#GRUB_TERMINAL=console

# The resolution used on graphical terminal
# note that you can use only modes which your graphic card supports via VBE
# you can see them in real GRUB with the command `vbeinfo'
#GRUB_GFXMODE=640x480

# Uncomment if you don't want GRUB to pass "root=UUID=xxx" parameter to Linux
#GRUB_DISABLE_LINUX_UUID=true

# Uncomment to disable generation of recovery mode menu entries
#GRUB_DISABLE_RECOVERY="true"

# Uncomment to get a beep at grub start
#GRUB_INIT_TUNE="480 440 1"

intel_iommu=on
iommu=pt
```
But now the touchbar is off. I tried running again `sudo modprobe apple-touchbar` and the touchbar ligths up and fn key works even after I close the lid ! I don't know if i will need to run this at every boot ? 

Thanks a lot !

**Comment by AdityaGarg8** [comment]
If you think touchbar now works, firstly turn on the touchbar using `sudo modprobe apple-touchbar`. Then run `sudo touchbar` and choose the mode you wish to have. This will remove the blacklist as well.

After doing this restart, and check whether touchbar is really working properly now or not. In either case, tell me the results and share `cat /proc/cmdline` again.

**Comment by AdityaGarg8** [comment]
```GRUB_CMDLINE_LINUX_DEFAULT="quiet splash intel_iommu=on iommu=pt"```

You have to do this

NOT what you have done

**Comment by Tyflomate** [comment]
Well done :ok_hand: The touchbar/fn key works as expected ! 
Here the content of cmdline:
```
➜  ~ cat /proc/cmdline
BOOT_IMAGE=/boot/vmlinuz-6.1.9-t2-jammy root=UUID=3f9efa86-1b8c-41e1-a6d0-bca150b3c7ef ro quiet splash intel_iommu=on iommu=pt vt.handoff=7
```

**Comment by AdityaGarg8** [comment]
Nice to hear that.

Just to be very sure, test suspend again. If you are good, then you may close this issue.

**Comment by Tyflomate** [comment]
Yes I did and now everything is okay, thanks a lot !
