### ISSUE TITLE
The Wireless Card is dropping a lot of packets

### ISSUE THREAD

**Issue by Sprungles** [t2linux/wiki#402]
Note on the *Bonus* section: We have access to the internet for sure, as stated (as I am writing this issue on a macbook pro 15,1 with Arch Linux), but as I was playing games, i noticed large amounts of stutter, which means packet loss. I then proceeded to use wireshark, and the current iteration of driver is dropping a large amount of packets. Again, it is usable to get onto the internet, but if you have any idea of why the broadcom chip is dropping so many packets, please let us know!

**Comment by NoaHimesaka1873** [comment]
Moved to relevant repo and reopened.

**Comment by sharpenedblade** [comment]
> Note on the _Bonus_ section: We have access to the internet for sure, as stated (as I am writing this issue on a macbook pro 15,1 with Arch Linux), but as I was playing games, i noticed large amounts of stutter, which means packet loss. I then proceeded to use wireshark, and the current iteration of driver is dropping a large amount of packets. Again, it is usable to get onto the internet, but if you have any idea of why the broadcom chip is dropping so many packets, please let us know!

Are you sure this isnt your network. Also do you have anything that can cause interference near you, the wireless AP, or somewhere nearby.

**Comment by Redecorating** [comment]
another thing to check if there's any relevant messages or errors that show up in `journalctl -kf` when you are having packets dropped.

also if you haven't already, see if updating linux helps.

**Comment by Sprungles** [comment]
I went ahead and checked to see if it was my network. The network in my area was having issues, but then began to troubleshoot why I was having difficulties. The drivers are perfect, and well, these devices weren't exactly designed with Linux in mind. I currently have pacman.conf set to only take kernels from the kernel repos for the t2. Thanks again, feel free to close the issue.
