### ISSUE TITLE
Adding install step for bluetooth on Arch/EndeavourOS

### ISSUE THREAD

**Issue by hobbesjaap** [t2linux/wiki#406]
Hi, I've successfully installed EndeavourOS on my Mac Mini 2018 (loving it, thank you so so so much). I wasn't able to use Bluetooth and after help from @Redecorating on Discord, I learned it isn't enabled by default on Arch(-derivatives).

The command `sudo systemctl enable --now bluetooth` made it work without any issue. Would it be worth adding this to the EndeavourOS installation guide?

Thank you all for you hard work with this, it's great to be able to properly use this MacMini, finally!!

**Comment by NoaHimesaka1873** [comment]
For Arch, I didn't add it since I intended users to read ArchWiki for their needed feature, just providing the base (in this case, Wi-Fi/Bluetooth firmware) to follow it.
