### ISSUE TITLE
Copy Wifi Firmware Script is Incompatible with older Versions of MacOS

### ISSUE THREAD

**Issue by MarjaE2** [t2linux/wiki#435]
I'm not sure where to report this.

The pre-installation instructions say to run a script to copy the wifi firmware: https://wiki.t2linux.org/guides/preinstall/#copy-wi-fi-firmware

This script is incompatible with older versions of MacOS, and the instructions don't include options for users who can't use newer versions of MacOS. Tghe error message states:

"This script is compatible only with macOS Monterey or later. Please upgrade your macOS."

I cannot switch to a newer MacOS without making the Finder and other apps painfully unreadable.

**Comment by sharpenedblade** [comment]
> I'm not sure where to report this.
> 
> The pre-installation instructions say to run a script to copy the wifi firmware: https://wiki.t2linux.org/guides/preinstall/#copy-wi-fi-firmware
> 
> This script is incompatible with older versions of MacOS, and the instructions don't include options for users who can't use newer versions of MacOS. Tghe error message states:
> 
> "This script is compatible only with macOS Monterey or later. Please upgrade your macOS."
> 
> I cannot switch to a newer MacOS without making the Finder and other apps painfully unreadable.

https://github.com/AdityaGarg8/Apple-Firmware

**Comment by MarjaE2** [comment]
Which refers to the wiki with the unusable instructions.

**Comment by sharpenedblade** [comment]
> Which refers to the wiki with the unusable instructions.

Go to releases, download the files, and look at the instructions in the release notes

**Comment by MarjaE2** [comment]
I'm not seeing any release-specific instructions: https://github.com/t2linux/t2linux-fedora-iso

**Comment by sharpenedblade** [comment]
This one https://github.com/AdityaGarg8/Apple-Firmware/releases/tag/Ventura

**Comment by MarjaE2** [comment]
I *think* I know which files to copy, but I don't know where to put them so that the .iso can complete installation.

**Comment by sharpenedblade** [comment]
> I _think_ I know which files to copy, but I don't know where to put them so that the .iso can complete installation.

You dont need them for the ISO, you need them for wifi on the installed system. They go in `/usr/lib/firmware/brcm`

**Comment by MarjaE2** [comment]
If I follow the instructions here, I get "no such file or directory."

https://wiki.t2linux.org/guides/wifi-bluetooth/

    The second method is to simply run the following commands on Linux :-

sudo umount /dev/nvme0n1p1
sudo mkdir /tmp/apple-wifi-efi
sudo mount /dev/nvme0n1p1 /tmp/apple-wifi-efi
bash /tmp/apple-wifi-efi/firmware.sh

If I try to copy the files into /usr/lib/firmware/brcm instead, I don't have the appropriate permissions and don't know how to get sudo to work in the gui.

**Comment by Samir-Rashid** [comment]
You can try running the [script](https://wiki.t2linux.org/tools/firmware.sh) on Linux and sending the output here if it fails @MarjaE2 
Can you explain what you mean by sudo not working? What command did you run that sudo did not work.

**Comment by MarjaE2** [comment]
I was initially unable to install from the live usb, and thought the lack of wifi might be responsible.

On the live usb, using sudo + command, the system did not ask for a password, and then rejected one of these commands for lack of permissions.

I was wrong, and after resetting Pram, I was able to install from there.

I still don't have wifi.

The 1st set of instructions for wifi, to run from MacOS, failed because they were incompatible with older versions of MacOS. I can't use newer versions, because they trigger my migraines. I had to find the files elsewhere.

The 2nd set of instructions, to run from Linux, failed as well, because there is no "firmware.sh".

**Comment by MarjaE2** [comment]
... And least, not in the listed location.

Sorry I can't edit comments on this site, because of how it handles scrolling.

**Comment by MarjaE2** [comment]
If I copy the firmware.sh file over, and try to run it, it reports success, but then I get recurring "Connection failed" alerts.

**Comment by AdityaGarg8** [comment]
As long as you do not have macOS Monterey or later, the only option remains is the GitHub repo linked by @sharpenedblade.

Clone the repo and copy all the firmware files to `/usr/lib/firmware/brcm`

**Comment by MarjaE2** [comment]
I can't copy files to there.

I've copied the files to a shared partition. I would get an error message when trying to copy to /usr/lib/firmware/brcm .

I've since copied them to my downloads folder. I don't get an error message when trying to copy from there to /usr/lib/firmware/brcm but I do get pain/animation of them returning.

**Comment by MarjaE2** [comment]
I'm considering trying these instructions tomorrow: https://www.amirootyet.com/post/how-to-get-wifi-to-work-after/

**Comment by sharpenedblade** [comment]
> I'm considering trying these instructions tomorrow: https://www.amirootyet.com/post/how-to-get-wifi-to-work-after/

Those are old instructions, they *probably* wont work.f

**Comment by MarjaE2** [comment]
The instructions in the wiki definitely haven't worked.

And manually copying the files hasn't. I assume there's a command-line method which works with sudo, but I don't know what it is. I suppose there's also a step to activate them after moving them, but I don't know what that step is either. Maybe that's where the firmware.sh actually works.

**Comment by sharpenedblade** [comment]
Run these commands in a terminal:
```bash
cd ~/Downloads
wget "https://github.com/AdityaGarg8/Apple-Firmware/archive/refs/heads/main.tar.gz"
tar -xf *.tar.gz
cd Apple-Firmware-main
cd lib/firmware/brcm
sudo cp -r * /usr/lib/firmware/brcm/
sudo modprobe -r brcmfmac
sudo modprobe brcmfmac
sudo modprobe -r hci_bcm4377
sudo modprobe hci_bcm4377
```

**Comment by MarjaE2** [comment]
Thanks.

I fucked that up because I couldn't read the terminal and mis-typed. Now I need to undo.

**Comment by AdityaGarg8** [comment]
The script has been updated to support older macOS versions.
