### ISSUE TITLE
EOS ships with Bluetooth disabled

### ISSUE THREAD

**Issue by smileBeda** [t2linux/wiki#483]
https://wiki.t2linux.org/guides/wifi-bluetooth/ says:
> If you're running Arch or EndeavourOS and have apple-bcm-firmware installed, you do not need to follow this guide. 

But that is not true, at least the T2 EOS disables Bluetooth to 100% and you need to `systemctl enable --now bluetooth` to even be able to trun on/off bluetooth.
Only then Bluetooth will actually work and allow you to tur it on/off,connect or tether.

Let me know if it is OK to make a PR to add said notice.

**Comment by NoaHimesaka1873** [comment]
WONTFIX. That guide is for installing firmware. Bluetooth shipping disabled is EOS upstream default behavior. You are free to make suggestion to them.

**Comment by AdityaGarg8** [comment]
There must be some reference for this information in the wiki then, maybe in the EOS part?

**Comment by smileBeda** [comment]
Well the reason is this https://duckduckgo.com/?q=bluetooth+vulnerabilities&iar=news&ia=news

But I think it’s misleading saying “it works” when it doesn’t.
All I intended was adding a notice about Bluetooth _not working_ out of the box.

I guess people can find out (the harder way) via asking in eos forum like I did:
https://forum.endeavouros.com/t/how-to-actually-share-a-file-via-bluetooth/48795/3

**Comment by AdityaGarg8** [comment]
You may pr. I'll see if it's worth it.

**Comment by NoaHimesaka1873** [comment]
> But I think it’s misleading saying “it works” when it doesn’t specially mentioning the distro which didn’t fix the vulnerability. All I intended was adding a notice about Bluetooth _not working_ out of the box.

Still, you don't have to follow that guide. Nowhere it mentions that it works out of the box. It just suggests that user don't have to follow *that particular guide* to enable Bluetooth. Might be worth adding it to install guide though, not the firmware guide.

**Comment by NoaHimesaka1873** [comment]
Also this is a duplicate of #406.

**Comment by smileBeda** [comment]
No one asks for it to be enabled 
Indeed thou the place I suggested for the notice is wrong.

Thanks for adding it to the install guide, I think it’s going to avoid a few “not working” complains.
