### ISSUE TITLE
dnf system-upgrade?

### ISSUE THREAD

**Issue by kaber2** [t2linux/wiki#489]
Hello,

couldn't ifnd anything related to this in the documentation - is it possible to upgrade to F39 using dnf system-upgrade?

Thanks!

**Comment by sharpenedblade** [comment]
You should ask on the discord or in the issue tracker at https://github.com/t2linux/fedora.

If you are using the [t2linux/fedora-iso](https://github.com/t2linux/fedora-iso) ISO, you need to run `sudo dnf install copr-sharpenedblade-t2linux-release --nogpgcheck && sudo dnf remove t2linux-repo`, then upgrade with `dnf system-upgrade` or gnome software. You only need to run this for fedora 38 -> 39, it will work normally in the future.
