### ISSUE TITLE
How about a multilingual translation for the T2 Linux wiki?

### ISSUE THREAD

**Issue by zeroday0619** [t2linux/wiki#50]
It would be good if the T2 Linux wiki supports multiple languages.

**Comment by networkException** [comment]
I don't really see the need for supporting multiple languages. Maintaining this would grow the amount of work exponentially for quite a small impact for users. Knowing english is a defacto requirement on the internet and this is especially true for the tech and even more true for the linux community.

Additioanally current maintainers (so mostly me) of this wiki would have to know the language to check for errors, misinformation and similar
