### ISSUE TITLE
Audio setup instructions assume a laptop

### ISSUE THREAD

**Issue by MarjaE2** [t2linux/wiki#501]
https://wiki.t2linux.org/guides/audio-config/

If sed -n "s/.*\(AppleT2.*\) -.*/\1/p" /proc/asound/cards has no result, they say to install bce for a built-in Apple keyboard, and refer users to:

https://wiki.t2linux.org/guides/postinstall/#installing-modules

Which also refers to a built-in Apple keyboard in Debian builds and errors out in Fedora with bash: /etc/initramfs-tools/modules: No such file or directory

**Comment by sharpenedblade** [comment]
> If sed -n "s/.(AppleT2.) -.*/\1/p" /proc/asound/cards has no result, they say to install bce for a built-in Apple keyboard, and refer users to:

This only works with the recent kernels with our [patches](https://github.com/t2linux/linux-t2-patches) installed.

> Which also refers to a built-in Apple keyboard in Debian builds and errors out in Fedora with bash: /etc/initramfs-tools/modules: No such file or directory

This only works on Debian, on Fedora you use `dracut`. Fedora already has a kernel with these patches so you dont need to do it yourself.

**Comment by MarjaE2** [comment]
> Firstly, check whether you are using an updated apple-bce version by running sed -n "s/.*\(AppleT2.*\) -.*/\1/p" /proc/asound/cards. If the output is AppleT2xN (where N is a number), then this guide can be followed. If it's just AppleT2, then either update the driver first or follow the [older version](https://github.com/t2linux/wiki/blob/00e882d0d5afb3102aedd02872426dc5fba789a5/docs/guides/audio-config.md) of this guide.

The next time around, the sed command worked. I don't know why it hadn't worked before.

I'm now showing 2 audio devices, though only the monitor's can make any sound.

**Comment by sharpenedblade** [comment]
Install the `t2linux-audio` package from the Fedora COPR and see if it works.

**Comment by MarjaE2** [comment]
It turned out grub was loading the standard Fedora rather than the t2 version. Picking the t2 version in grub got the built-in audio working, but not the audio jack.

**Comment by sharpenedblade** [comment]
Install easyeffects and check if it exists as a device

**Comment by MarjaE2** [comment]
Easyeffects Sink shows up; the headphones do not.

**Comment by sal4org** [comment]
Hi, GREAT WORK!

i have applayed the configs for the audio with esayeffects, and the sound is muche better, but ther is a caviat: only sounr from letft side speakers. I´m fedora40-mbp iso and macbookpro16,1.
Thanks in advance for you help

**Comment by AdityaGarg8** [comment]
Closing it as stale. Reopen if required @MarjaE2
