### ISSUE TITLE
Following debian t2 installation guide:  `E: Unable to locate package tiny-dfr`

### ISSUE THREAD

**Issue by s4Dt0y** [t2linux/wiki#531]
I am following [this](https://wiki.t2linux.org/distributions/debian/installation/) guide. I have run the update_t2_kernel command without errors (although it took a lot of work and debugging to get there...). My wifi is working as expected. The problem is that when I try to run
```
sudo apt install tiny-dfr
```
I get the error `Unable to locate package tiny-dfr`. I am pretty sure I added the correct repo with the following command:
```
curl -s --compressed "https://adityagarg8.github.io/t2-ubuntu-repo/KEY.gpg" | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/t2-ubuntu-repo.gpg >/dev/null
sudo curl -s --compressed -o /etc/apt/sources.list.d/t2.list "https://adityagarg8.github.io/t2-ubuntu-repo/t2.list"
sudo apt update
```
In fact, I took a look at the repo added to the sources, and tiny-dfr is not present there...Perhaps there is a mistake in the docs?

Is there anyone who can help me find out what I'm doing wrong here? I am really itching to not have to carry a wired keyboard and mouse with me everywhere. Thanks!

**Comment by AdityaGarg8** [comment]
> I am following [this](https://wiki.t2linux.org/distributions/debian/installation/) guide. I have run the update_t2_kernel command without errors (although it took a lot of work and debugging to get there...). My wifi is working as expected. The problem is that when I try to run
> 
> ```
> sudo apt install tiny-dfr
> ```
> 
> I get the error `Unable to locate package tiny-dfr`. I am pretty sure I added the correct repo with the following command:
> 
> ```
> curl -s --compressed "https://adityagarg8.github.io/t2-ubuntu-repo/KEY.gpg" | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/t2-ubuntu-repo.gpg >/dev/null
> sudo curl -s --compressed -o /etc/apt/sources.list.d/t2.list "https://adityagarg8.github.io/t2-ubuntu-repo/t2.list"
> sudo apt update
> ```
> 
> In fact, I took a look at the repo added to the sources, and tiny-dfr is not present there...Perhaps there is a mistake in the docs?
> 
> Is there anyone who can help me find out what I'm doing wrong here? I am really itching to not have to carry a wired keyboard and mouse with me everywhere. Thanks!

tiny-dfr is available only for Ubuntu and it's derivatives like Linux mint and Pop os, not debian. Sorry I forgot to update the docs.

For Debian, you have to run this:

```
cat <<EOF | sudo tee /etc/modprobe.d/tiny-dfr.conf
blacklist appletbdrm
blacklist hid_appletb_kbd
blacklist hid_appletb_bl
EOF
sudo apt install apple-touchbar
```

**Comment by AdityaGarg8** [comment]
Update:

tiny-dfr has been released for Debian. Visit https://github.com/AdityaGarg8/t2-ubuntu-repo/tree/main?tab=readme-ov-file#apt-repository-for-t2-macs to get the new apt repo hosting it.
