### ISSUE TITLE
audio with esayeffects only on left side speakers

### ISSUE THREAD

**Issue by sal4org** [t2linux/wiki#555]
Hi, GREAT WORK!

i have applayed the configs for the audio with esayeffects, and the sound is muche better, but ther is a caviat: only sound from letft side speakers. I´m fedora40-kde-mbp iso and macbookpro16,1.
Thanks in advance for you help

**Comment by AdityaGarg8** [comment]
I'll suggest using dsp for 16,1

https://github.com/lemmyg/t2-apple-audio-dsp/tree/speakers_161
