### ISSUE TITLE
Move instructions for /etc/systemd/system-sleep/unload-wifi.sh outside of Fedora-specific FAQ

### ISSUE THREAD

**Issue by dullbananas** [t2linux/wiki#570]
I needed it in Debian

Also idk if it requires `chmod +x` but if it does then that should be documented

**Comment by AdityaGarg8** [comment]
If you want to change something, open a PR, not an issue.

**Comment by dullbananas** [comment]
Based on further testing, it seems like this actually doesn't work in Debian. But I did get Wi-Fi after suspend to work by changing suspend-fix-t2.service to contain the systemctl commands that unload-wifi.sh has. I will make that change in the wiki. I'm guessing the unload-wifi.sh instructions should be removed because it's redundant, is that correct?

**Comment by AdityaGarg8** [comment]
> Based on further testing, it seems like this actually doesn't work in Debian. But I did get Wi-Fi after suspend to work by changing suspend-fix-t2.service to contain the systemctl commands that unload-wifi.sh has. I will make that change in the wiki. I'm guessing the unload-wifi.sh instructions should be removed because it's redundant, is that correct?

They are the same as making a service, so no, they are correct.

**Comment by dullbananas** [comment]
I take that back. Neither method completely fixed the problem.

**Comment by dullbananas** [comment]
I'm now trying `nmcli radio wifi off` and `nmcli radio wifi on`

**Comment by dullbananas** [comment]
Now trying `RUNTIME_PM_DISABLE` in `tlp.conf` (if it works, I will explain it in my PR)

**Comment by dullbananas** [comment]
trying `apt install firmware-brcm80211/bookworm-backports`
