### ISSUE TITLE
"Basic setup" and "Debian, Pop!_OS and other similar distros" suggest different values for pcie_ports

### ISSUE THREAD

**Issue by dullbananas** [t2linux/wiki#574]

**Comment by AdityaGarg8** [comment]
I'd appreciate if you describe your issue.

**Comment by dullbananas** [comment]
https://t2linux.org/guides/postinstall/ has pcie_ports=compat

https://t2linux.org/distributions/debian/installation/ has pcie_ports=native

**Comment by AdityaGarg8** [comment]
Follow pcie_ports=native

**Comment by igorsantos07** [comment]
That got me confused as well, while trying to troubleshoot sound issues - `pcie_ports=compat` is also suggested on the Audio guide, while also the Audio guide doesn't suggest installation of `apple-t2-audio-config`, which the Debian guide does :thinking:

**Comment by AdityaGarg8** [comment]
`apple-t2-audio-config` is basically a shortcut way to follow the audio guide
