### ISSUE TITLE
Ubuntu+Guides: Remove redundant FAQ entries

### ISSUE THREAD

**Issue by networkException** [t2linux/wiki#6]
As general guides for Windows Tripple Boot and DKMS / Audio were just added, could you (@EmreTech) maybe see how much information is already contained in the new guides that you can remove from the FAQ (maybe also add more things to the guides thats in the faq right now, as I don't know much about the technical details could you (@Redecorating) review in that case)?

I'd like to especially make sure that we don't have duplicate information in this wiki and rather provide one place for detailed documentation per topic.

**Comment by EmreTech** [comment]
Sorry I didn't do this earlier. I didn't see this
