### ISSUE TITLE
Hybrid graphics not working on MBP 16,1

### ISSUE THREAD

**Issue by fetushito** [t2linux/wiki#66]
Going through the hybrid graphics configuration steps, I'm getting stuck at step [#3](https://wiki.t2linux.org/guides/hybrid-graphics/) where the "spoof" efi file loads but fails to load the original efi file. It shows a message like "Unable to boot bootx64_original.efi".

I am running dual-boot (Big Sur & Ubuntu) through refind. I would like to hear ideas on how to troubleshoot and resolve this, as the macbook is heating a lot due to the main graphic card being active all the time. Battery usage is also dramatically affected by this.

**Comment by Redecorating** [comment]
did you move refind to efi/boot/bootx64_original.efi? i think refind might not put itself at efi/boot/bootx64.efi, so you may have to move a different file (probably called refindx64.efi or something similar) to bootx64_original.efi

**Comment by fetushito** [comment]
I was able to achieve the desired behavior through the `spoof_osx_version` version [rEFInd](https://rodsbooks.com/refind/configfile.html) provides.

**Comment by fetushito** [comment]
Researching more on the topic I realized that by using the `spoof_osx_version` refind option while blacklisting the amdgpu module under `/etc/modprobe.d/blacklist.conf` I was effectively making my system boot with the CPU taking care of graphics, similar to what's described [here.](https://gist.github.com/gbrow004/096f845c8fe8d03ef9009fbb87b781a4#gistcomment-3297643)

The EFI paths and file names described in this wiki differ a little bit from what I have on my EFI partition, but regardless, rEFINd should scan the files there too, so I don't think that's the problem. The boot files my installation uses are under `/boot/efi/EFI/refind` while the wiki here shows `/boot/efi/efi/boot/`.

Not sure how to degug this or what else to try in order to deactivate amdgpu dGPU and initalise the Intel iGPU as opposed to the CPU.

**Comment by Redecorating** [comment]
I've found that the dgpu uses more power when `amdgpu` isn't loaded, so you may want to not blacklist it (the dgpu probably gets put into a better power saving state by `amdgpu`).

For debugging this:

- Is the igpu present in `lspci` when you use refind's spoof osx thing?
- What's the output of `DRI_PRIME=1 glxinfo | grep "OpenGL renderer" && glxinfo | grep "OpenGL renderer"`, if you don't blacklist `amdgpu`?
- `journalctl -b --grep=i915`
- Have you set the `gpu-power-prefs` nvram variable since you last booted into macOS? It gets reset and needs to be set to 1 for the display to be connected to the igpu

**Comment by AdityaGarg8** [comment]
Share the path which rEFInd shows when you select Ubuntu.

**Comment by fetushito** [comment]
>     * DRI_PRIME=1 glxinfo | grep "OpenGL renderer" && glxinfo | grep "OpenGL renderer"

Standard boot:

`DRI_PRIME=1 glxinfo | grep "OpenGL renderer" && glxinfo | grep "OpenGL renderer"` output:

```OpenGL renderer string: AMD NAVI14 (DRM 3.40.0, 5.10.47, LLVM 11.0.1)
OpenGL renderer string: AMD NAVI14 (DRM 3.40.0, 5.10.47, LLVM 11.0.1)```

Intel GPU is not present when running `lspci` command.

Boot with rEFInd's spoof macos option enabled:

`DRI_PRIME=1 glxinfo | grep "OpenGL renderer" && glxinfo | grep "OpenGL renderer"` output:

```OpenGL renderer string: AMD NAVI14 (DRM 3.40.0, 5.10.47, LLVM 11.0.1)
OpenGL renderer string: AMD NAVI14 (DRM 3.40.0, 5.10.47, LLVM 11.0.1)```

Intel GPU is not present when running `lspci` command.

**Comment by fetushito** [comment]
Looks like the nvram setting was the issue. Here the new output after setting it back again:

# DRI_PRIME=1 glxinfo | grep "OpenGL renderer" && glxinfo | grep "OpenGL renderer"
OpenGL renderer string: AMD NAVI14 (DRM 3.40.0, 5.10.47, LLVM 11.0.1)
OpenGL renderer string: Mesa Intel(R) UHD Graphics 630 (CFL GT2)

lspic shows iGPU:

00:02.0 VGA compatible controller: Intel Corporation CoffeeLake-H GT2 [UHD Graphics 630] (rev 02)

`# journalctl -b --grep=i915` also shows some entries now. Am I already with a perfect setup or are there any other steps required? :)

**Comment by Redecorating** [comment]
you can add the `i915.enable_guc=2` kernel argument to save a little bit of power, but if it's able to render with the igpu then you're good!

**Comment by fetushito** [comment]
Awesome! Will the kernel now switch between the two according to the need or will it always be under the iGPU unless I change back the applied settings?

**Comment by Redecorating** [comment]
Anything run with `DRI_PRIME=1` as an environment variable will be rendered on the dgpu. Some applications will do this automatically (i.e. games), but the default will be for things to render on the iGPU.

**Comment by fetushito** [comment]
Ok, cool. I just noticed that after plugging the second monitor, the system crashes. Is this a known tradeoff or something specific to my config perhaps?

**Comment by Redecorating** [comment]
try the kernel argument `amdgpu.dpm=0`, especially if upon rebooting into macos it reports a "CPU CATERR". This does increase power consumption a bit.

**Comment by fetushito** [comment]
Thanks a lot. Excuse my ignorance, but where can I tweak the `amdgpu.dpm=0` setting? In the kernel `.config` file when rebuilding the kernel?

**Comment by Redecorating** [comment]
That'll be when your bootloader starts the kernel. for grub that's /etc/default/grub, but I don't know what it is for refind.

**Comment by fetushito** [comment]
Ok, I'll look into rEFInd's documentation!

**Comment by fetushito** [comment]
Didn't help unfortunately. I set it up under refind_linux.config file:

"Boot with standard options" "root=UUID=[UID_GOES_HERE] cryptdevice=/dev/nvmeXnXpX:cryptroot:allow-discards ro rootfstype=ext4 quiet splash vt.handoff=7 amdgpu.dpm=0"

**Comment by Redecorating** [comment]
check if it shows up in `/proc/cmdline` on linux, and also you may want to add these kernel arguments: `pcie_ports=compat intel_iommu=on` for stability and better suspend.

**Comment by fetushito** [comment]
> check if it shows up in `/proc/cmdline` on linux, and also you may want to add these kernel arguments: `pcie_ports=compat intel_iommu=on` for stability and better suspend.

All of them do appear in the /proc/cmdline, however, they don't make any difference. Suspend is broken, the system never comes back after opening back the lid.

**Comment by Redecorating** [comment]
External monitors will be connected to the dgpu, so [reverse prime](https://wiki.archlinux.org/title/PRIME#Reverse_PRIME) should make them work, but there's some advice on the arch wiki for issues with it that may help.

**Comment by fetushito** [comment]
Thank you. I should look into it soon and report back.
